### PR TITLE
Bringing CAD1 recipe from v0.3.4 to main

### LINKED ISSUE #319: Bring CAD1 recipes improvements to main
The improvements done to recipes for CAD1, released in v0.3.2 aren't in the main branch.
Need to implement these in the main. cherry peak won't suffice are main diverged from v0.3.2

### PR DESCRIPTION
**Pull request by groadabike**
close #319 

This PR implements all improvements made in CAD1 from version 0.3.3 to the main branch to avoid branches from diverging.
It now includes changes from version 0.3.4

### CODE REVIEW

**Comment by groadabike** [comment]
@jonbarker68 
This PR are the changes we made for CAD 1 to bring it to MAIN

**Comment by groadabike** [comment]
@jonbarker68 is ready for review.
It is bringing version 0.3.4 to the main branch

Note that in ICASSP and here I am using a new class for the results `clarity/utils/results_support.py`
I created this class to avoid creating the same class in all `evaluate.py` where the only difference is the header's column names.
The `header` can be a param and the values can be sent in a dict

**Review by jonbarker68 — APPROVED** [review]
Thanks. Looks good to me. Forgot this one was waiting.

**Comment by groadabike** [comment]
It failed running Python 3.8 in test
```
=========================== short test summary info ============================
FAILED tests/regression/test_predictors.py::test_torch_msbg_stoi_xeon_e5_2673_cpu
```

**Comment by groadabike** [comment]
The second time, it was an urllib library error??
```
=========================== short test summary info ============================
FAILED tests/recipes/cad1/task1/baseline/test_enhance_task1.py::test_decompose_signal[separation_model1-True] - urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
===== 1 failed, 490 passed, 22 skipped, 4404 warnings in 152.30s (0:02:32) =====
```

**Comment by groadabike** [comment]
The errors are happening when requesting the open-unmix model from `torch.hub`. It is a 403 error.
The error is only in the workflow in GitHub, locally I can see the issue.
I am testing what happens if I apply this workaround
`https://github.com/pytorch/pytorch/issues/61755#issuecomment-885801511`

**Pull request merged**
