### PR TITLE
Printing cpuinfo in test

### PR DESCRIPTION
**Pull request by groadabike**
Signed-off-by: Gerardo Roa Dabike <gerardo.roa@gmail.com>

### CODE REVIEW

**Comment by groadabike** [comment]
Test pass with:
- model name	: AMD EPYC 7452 32-Core Processor
- model name	: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz

And failed with:
- model name	: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
The reason of failure is:
```
=================================== FAILURES ===================================
_____________________________ test_torch_msbg_stoi _____________________________

regression test output differences for tests/regression/test_predictors.py::test_torch_msbg_stoi:

>   --- current
>   +++ tobe
>   @@ -1,2 +1,2 @@
>   -Torch MSBG STOILoss -0.46198, ESTOILoss -0.32999
>   +Torch MSBG STOILoss -0.46198, ESTOILoss -0.33000
```

**Comment by ns-rse** [comment]
Thanks for investigating this @groadabike and interesting to see what the tests are passing/failing on now its pegged to CPU on the limited runs so far its the Xeon E5-2673 that fails.


| Chip         | Pass / Fail            |
|--------------|:------------------:|
| AMD EPYC 7452 32-Core Processor | :heavy_check_mark: |
| Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz | :heavy_check_mark: |
| Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.30GHz | :no_entry: |
| Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz | :no_entry: |


I'm no expert on this but have done some digging on the hardware that actions run on.

[About GitHub-hosted runners - GitHub Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) indicates that Windows and Linux run on...

* 2-core CPU (x86_64)
* 7GB RAM
* 14GB SSD

But it also states that [Dv2 and DSv2-series](https://docs.microsoft.com/azure/virtual-machines/dv2-dsv2-series#dsv2-series) provided by Azure are used to host runners and it is these that run on Xeon chips it seems.


One thing to note though as this is unlikely to be merged is that you can create "Draft Pull Request" (use the arrow next to "Create Pull Request" when first creating) and this will still run the tests and allow failed Actions to be re-run.

**Comment by groadabike** [comment]
Hi @ns-rse,

As @jonbarker68 proposed [here](https://github.com/claritychallenge/clarity/pull/123#issuecomment-1324154208), we could use this cpuinfo to point to a different `_regtest_outputs` directory for the regression tests depending on the chip assigned.

I am not sure if that is possible or even a good practice. 
What are your thoughts about it?

**Comment by ns-rse** [comment]
I think that's a really good suggestion @jonbarker68 has made.

Reading the [pytest-regtest](https://gitlab.com/uweschmitt/pytest-regtest) documentation I don't think it will be possible to resolve there (and development/activity is slow, I made a Merge Request three weeks ago to include `py` as a dependency after it was removed as such from `pytest`).

However, it may be possible to control this from the `.github/workflows/run_tests.yaml` by detecting the CPU and conditionally running tests.

I'll have a look at this over the coming days.

**Comment by ns-rse** [comment]
I've merged #135 and incorporated a check for the CPU tests are being run on in the GitHub Action/workflow to help in the future.

Thanks for your help investigating this @groadabike :+1:

**Pull request closed without merging**
