### PR TITLE
Adding Badges to Head of Readme

### LINKED ISSUE #146: Add badges in Readme
Add badges to Clarity/Cadenza Readme for fast Toolkit information

### PR DESCRIPTION
**Pull request by groadabike**
Signed-off-by: Gerardo Roa Dabike <gerardo.roa@gmail.com>
Closes #146 

PR is adding badges below the Clarity and Cadenza figures:

The current badges are:
* First row:
1. Last pip version
2. Python versions. The versions are obtained automatically, not sure yet how to specify a specific version like  ` 3.7 | 3.8 | 3.9 | 3.10`  Eg. like in https://github.com/asteroid-team/asteroid
3. Code style Black
4. Number of downloads

* Second Row
There are 2 badges that specify the pip version with the challenges. These are custom badges that we can change in colours and texts

Note, I didn't include this commit in @jonbarker68 Readme PR to avoid conflicts with that branch

### CODE REVIEW

**Review by ns-rse — APPROVED** [review]
Neat, looks good.

May well borrow this structure in the future, badges isn't something I've had recourse to use much before.

**Review by jonbarker68 — APPROVED** [review]
Thanks! I like this. 

Made a tiny edit to improve spacing/centering.

**Comment by groadabike** [comment]
By the way, I am not sure how that info is included, but the badge with the python versions seems to be taking the information from `Programming Language` in pypi.
In [pyclarity](https://pypi.org/project/pyclarity/) it says
```
Programming Language
[Python :: 3]
```

But, in [Asteroid](https://pypi.org/project/asteroid/), they specify specific versions. 
```
Programming Language
[Python :: 3]
[Python :: 3.10]
[Python :: 3.8]
[Python :: 3.9]
```
We may want to do that to match the versions we use for the tests and show that info in the badge

**Comment by ns-rse** [comment]
You could perhaps include a code coverage badge. It would involved tweaking the `.github/workflow/run_tests.yaml` to use the [coverage-py-badge](https://github.com/marketplace/actions/coverage-py-badge) action.

By the way if you start your PR with a [GitHub Keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) it will close the issue automatically on merging. For example if you'd written the following at the start 

```
Closes #146 
```

...that would do the trick (you may be able to put it anywhere in the body but I typically try and put it at the top).

**Comment by ns-rse** [comment]
The `Programming Language` that PyPI uses is likely being pulled from `setup.cfg` in the `metadata` section...

```
classifiers=
    ...
    Programming Language :: Python :: 3
```

...and so adding the following would add the information..
```
classifiers=
    ...
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
```

I'd just be copying what Asterid have done to get that into a badge.

(Asteroid defines these in `setup.py` but that file is slowly being deprecated in favour of `setup.cfg` and `pyproject.toml`).

**Comment by groadabike** [comment]
> You could perhaps include a code coverage badge. It would involved tweaking the `.github/workflow/run_tests.yaml` to use the [coverage-py-badge](https://github.com/marketplace/actions/coverage-py-badge) action.

Hi @ns-rse, after a bit of reading, I found how to include the badge without effort.

**Comment by groadabike** [comment]
> By the way if you start your PR with a [GitHub Keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) it will close the issue automatically on merging. For example if you'd written the following at the start
> 
> ```
> Closes #146 
> ```
> 
> ...that would do the trick (you may be able to put it anywhere in the body but I typically try and put it at the top).

Thank you so much for the info. There are so many tricks in Github that I didn't know about it.
Just in case, I updated the first comment with `Closes #146`.

**Review by ns-rse — APPROVED** [review]
Looks great and thanks for including the codecov badge, my apologies for not giving a suggestion on how to do so.

**Comment by jonbarker68** [comment]
This is looking great. Are we happy to merge this now?

**Comment by groadabike** [comment]
> This is looking great. Are we happy to merge this now?

Yeah, They look great.
Happy to merge

**Pull request merged**
